### PR TITLE
Don't merge this pull request (at least until we figure out what's happening)

### PR DESCRIPTION
**Pull request by thundernixon**
As I said earlier, I was able to build a VF from the open sans designspace. Initially, I thought that I had properly pulled the latest laerm0/opensans state of the project, so I thought maybe I had cracked it.

_However,_ looking at this PR preview, I realized that I may have been judging a very incorrect state of the project. 

When I checkout the actual latest commit, bbe56eba, I find that I am getting the same fontmake failure:

```
INFO:fontTools.varLib:Generating GSUB FeatureVariations
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/opensans/venv/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.9.1', 'console_scripts', 'fontmake')()
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontmake/__main__.py", line 395, in main
    project.run_from_designspace(designspace_path, **args)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 865, in run_from_designspace
    **kwargs
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 921, in _run_from_designspace_interpolatable
    ttf_designspace, output_path=output_path, output_dir=output_dir
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 377, in build_variable_font
    font.save(output_path)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 70, in compile
    self.table.compile(writer, font)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 710, in compile
    conv.write(writer, font, table, value)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 681, in compile
    conv.write(writer, font, table, value, i)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 681, in compile
    conv.write(writer, font, table, value, i)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 650, in compile
    table = self.preWrite(font)
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otTables.py", line 723, in preWrite
    gidItems = [(getGlyphID(a), getGlyphID(b)) for a,b in items]
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/tables/otTables.py", line 723, in <listcomp>
    gidItems = [(getGlyphID(a), getGlyphID(b)) for a,b in items]
  File "/Users/stephennixon/type-repos/opensans/venv/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 602, in getGlyphID
    glyphID = d[glyphName]
KeyError: ('alefdagesh-hb', 'SingleSubst[0]', 'Lookup[34]', 'LookupList')
```

This is confusing to me, because the `alefdagesh-hb` and `alefdagesh-hb.rvrn` are in all masters, and so far as I can tell, the designspace rule is written correctly.

I can't spend more time on this now, but maybe there might be something in my files that provides a clue to what is throwing this off, so here's a PR to show the state of the project that built.

### CODE REVIEW

**Comment by laerm0** [comment]
As long as we're tracking this here, commenting out the `<rules>` in `OpenSans-Roman-quadratic.designspace` (lines 154-170) allows the TTF to build.

**Comment by anthrotype** [comment]
Right, so it is this issue here: https://github.com/fonttools/fonttools/issues/1349

basically, the problem is that the glyph names in your DesignSpace document rules use design or human-friendly names ("alefdagesh-hb"), but when you build binary fonts, the glyph names get automatically renamed by fontmake to what some calls "production" names, or what I prefer to call just postscript glyph names (i.e. following the [AGLFN spec](https://github.com/adobe-type-tools/agl-aglfn), e.g. in uniXXXX and such).

The glyph renaming step occurs in ufo2ft.postProcessor, using the UFO.lib["public.postscriptNames"] mapping. However the variable font building only happens later, after the individual master TTFs have been built, and now have (by default) final postscript glyph names.

I need to think about how to fix this in fontmake, but for now I recommend that you:

- either use the final postscript names for those glyphs in your DesignSpace rules, 
- or you pass `--no-production-names` when you build the variable font with fontmake (or the ttf-interpolatable). In that case, the variable font will not have the final postscript names in the post table.

**Comment by moyogo** [comment]
As a side note: You should normalize your UFOs before committing them. It make it easier to read diffs.

**Comment by laerm0** [comment]
Hey, great! Thanks @anthrotype .

I did not know that was a thing, @moyogo . Thank you, I'll use the tool at https://github.com/unified-font-object/ufoNormalizer

**Comment by anthrotype** [comment]
>  You should normalize your UFOs

_IFF_ you plan to use different UFO editors to write to those. If you stick to fontTools.ufoLib as the writer, you can treat its output as the "normalized" version. If you exported the UFOs from glyphs using glyphsLib (or fontmake, which in turns uses glyphsLib), that's the UFOWriter that is used under the hood.

**Pull request closed without merging**
